name: PR approved

on: [pull_request_target, issues]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Labeler
      uses: actions/labeler@v5.0.0
