# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-label merge conflicts  
      uses: mschilde/auto-label-merge-conflicts@v2.0
      with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
